completed solution16
Jayshgandhi/Java-learn pull request #16
Opened 2021-02-23 07:13 UTC by Jayshgandhi

Output:

Scalar multiplication:	[936]
Vector multiplication:	[115 402 801 225 ]
Matrix multiplication:
[	[6	12	1	]
	[20	42	4	]
	[1	4	9	]
]

2021-02-23 07:26 UTC, fr-judson requested changes
Logic is perfect and You should raise exception manually using throw keyword in the else block.
Understand about throw keyword in Java fix the issue.

2021-02-23 07:26 UTC, fr-judson commented on Exercises/Excercise16/solution16.java
> +            if (n.length == y.length) {
"If" case is not passed exception should be thrown.

2021-02-23 07:26 UTC, fr-judson commented on Exercises/Excercise16/solution16.java
> +            if (n.length == y.length) {
"if" case is not passed exception should be thrown.

2021-02-25 14:16 UTC, hockeyjudson approved these changes
LGTM

2021-02-25 14:17 UTC, merged