solution24 completed
Jayshgandhi/Java-learn pull request #24
Opened 2021-03-20 06:25 UTC by Jayshgandhi

Output:
Data value is: 20
Data value is: 20.22
Data value is: 125.332

2021-03-20 07:38 UTC, hockeyjudson requested changes
Where is the rest

2021-03-27 23:58 UTC, hockeyjudson requested changes

2021-03-27 23:58 UTC, hockeyjudson commented on Exercises/Excercise24/solution24.java
> +class Sample <T extends Number >{
Read the question once and complete it

2021-03-28 14:46 UTC, fr-judson approved these changes
LGTM

2021-03-28 14:47 UTC, merged