solution26 is completed
Jayshgandhi/Java-learn pull request #26
Opened 2021-03-21 14:47 UTC by Jayshgandhi

2021-03-21 16:00 UTC, fr-judson requested changes

2021-03-21 16:00 UTC, fr-judson commented on Exercises/Excercise26/solution26.java
> +        Name_generator ex = new Name_generator();
Include Name_generator code

2021-03-21 16:00 UTC, fr-judson commented on Exercises/Excercise26/solution26.java
> +        Collections.sort(e);
Implement this sorting part using java streams

2021-03-27 23:52 UTC, hockeyjudson approved these changes
LGTM

2021-03-27 23:52 UTC, merged