solution22 is completed
Jayshgandhi/Java-learn pull request #27
Opened 2021-03-21 14:48 UTC by Jayshgandhi

2021-03-21 15:57 UTC, fr-judson requested changes
Please fix these changes

2021-03-21 15:57 UTC, fr-judson commented on Exercises/Excercise22/solution22.java
> +        Name_generator ex = new Name_generator();
Include Name_generator code

2021-03-21 15:57 UTC, fr-judson commented on Exercises/Excercise22/solution22.java
> +    public List<String> numberOfFailures(List<Student> d,Integer passMarkThreshold){
Expected result is in integer of number of students failed on the exam

2021-03-25 04:09 UTC, fr-judson requested changes
LGTM

2021-03-25 04:09 UTC, fr-judson commented on Exercises/Excercise22/solution22.java
> +        List<Student> gt =s.subList(Math.max(s.size()-5,0), s.size());
Use stream to get last five students and print the students also using stream

2021-03-27 13:22 UTC, hockeyjudson requested changes

2021-03-27 13:22 UTC, hockeyjudson commented on Exercises/Excercise22/solution22.java
> +        List<Student> t = s.stream().skip(count-5).collect(Collectors.toList());
Use the same stream line to print

2021-03-27 13:23 UTC, hockeyjudson commented on Exercises/Excercise22/solution22.java
> +        List<Student> t = s.stream().skip(count-5).collect(Collectors.toList());
Also write code to handle the case for the number of elements less than five use if else

2021-03-27 13:24 UTC, hockeyjudson commented on Exercises/Excercise22/solution22.java
> +        List<Student> t = s.stream().skip(count-5).collect(Collectors.toList());
Stream print https://www.geeksforgeeks.org/how-to-print-elements-of-a-stream-in-java-8/

2021-03-27 23:55 UTC, hockeyjudson approved these changes
LGTM

2021-03-27 23:55 UTC, merged